extends:
    - "screwdriver"
    - "plugin:prettier/recommended"  # last one wins
rules:
    max-lines-per-function: "warn"
    complexity: "warn"
    max-params: "warn"
    max-statements: "warn"
    prefer-destructuring:
    - "warn"
    # - array: false
    #   object: true
    # - VariableDeclarator:
    #     array: false
    #     object: true
    #   AssignmentExpression:
    #     array: false
    #     object: true
